
#    Copyright 2018 Tech Bureau, Corp
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http:#www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

version: '2'
services:
  openvpn-client: 
    build: dockerfiles/openvpn-client
    command: openvpn --config /client/rich.ovpn
    privileged: true
    extra_hosts:
    - "vpn.my.fqdn:172.31.7.236"
    dns:
    - 10.96.0.10
    volumes:
    - ./client:/client

  ######  dynamic configuration  ###########

  generate-raw-addresses:
    image: techbureau/catapult-tools:gcc-0.2.0.2
    command: bash -c "/bin-mount/generate-raw-addresses-if-needed 50 /addresses/raw-addresses.txt /addresses/addresses.yaml"
    volumes:
    - ./bin/bash:/bin-mount
    - ./build/generated-addresses:/addresses:rw
    - ./build/state:/state:rw

  store-addresses:
    build: dockerfiles/ruby-alpine
    command: ash -c "/bin-mount/wait /addresses/raw-addresses.txt && /ruby/bin/store-addresses-if-needed.rb /addresses/raw-addresses.txt /addresses/addresses.yaml"
    volumes:
    - ./bin/ash:/bin-mount
    - ./ruby:/ruby
    - ./build/generated-addresses:/addresses:rw

  generate-configs:
    build: dockerfiles/ruby-alpine
    command: ash -c "/bin-mount/wait /addresses/addresses.yaml && /ruby/bin/generate-and-write-configurations.rb /addresses/addresses.yaml /config-build /nemesis && touch /state/configs-generated"
    volumes:
    - ./bin/ash:/bin-mount
    - ./ruby:/ruby
    - ./build/generated-addresses:/addresses
    - ./build/catapult-config:/config-build
    - ./build/nemesis:/nemesis:rw
    - ./build/state:/state:rw

  ###### running services ###########

  peer-node-0-nemgen:
    build: dockerfiles/nemgen
    command: bash -c "sleep 1000000"
#    command: bash -c "/bin-mount/wait /state/configs-generated && /bin/bash /userconfig/nemgen.sh && touch /state/peer-node-0-nemgen"
    stop_signal: SIGINT
    volumes:
    - ./build/catapult-config/peer-node-0/userconfig/resources/:/userconfig/resources/
    - ./build/nemesis/:/nemesis
    - ./data/peer-node-0:/data:rw
    - ./bin/bash:/bin-mount
    - ./build/state:/state:rw
    depends_on:
    - generate-configs

  peer-node-0:
    build: dockerfiles/catapult
#    command: bash -c "/bin-mount/wait /state/peer-node-0-nemgen && /bin/bash /userconfig/startServer.sh"
    command: bash -c "sleep 1000000"
    dns:
    - 10.96.0.10
    stop_signal: SIGINT
    volumes:
    - ./build/catapult-config/peer-node-0/userconfig/resources/:/userconfig/resources/
    - ./data/peer-node-0:/data:rw
    - ./bin/bash:/bin-mount
    - ./build/state:/state
    depends_on:
    - generate-configs
    - peer-node-0-nemgen

