#!/bin/bash

build_param=$1

if [ "$build_param" == "--build" ]; then
  docker-compose -f cmds/docker/catapult-api-broker.yml up --build
else
  docker-compose -f cmds/docker/catapult-api-broker.yml up
fi
